export const WorkoutPlanData = [
  {
    id: '1',
    title: 'Day 1',
    content: 'Shoulders, Chest, and Core',
    bg: 'grade1',
    exercises: [
      {
        id: '1',
        name: 'Barbell Shoulder Press',
        reps: '10-12',
        sets: '4',
        image: require('../assets/images/BarbellShoulderPress.gif'),
      },
      {
        id: '2',
        name: 'Bench Press',
        reps: '8-10',
        sets: '4',
        image: require('../assets/images/BenchPress.gif'),
      },
      {
        id: '3',
        name: 'Dumbbell Flyes',
        reps: '12-15',
        sets: '3',
        image: require('../assets/images/DumbbellFlyes.gif'),
      },
      {
        id: '4',
        name: 'Plank',
        reps: '30 seconds',
        sets: '3',
        image: require('../assets/images/Plank.gif'),
      },
      {
        id: '5',
        name: 'Russian Twists',
        reps: '15-20',
        sets: '3',
        image: require('../assets/images/RussianTwists.gif'),
      },
    ],
  },
  {
    id: '2',
    title: 'Day 2',
    content: 'Legs and Back',
    bg: 'grade2',
    exercises: [
      {
        id: '1',
        name: 'Squats',
        reps: '8-10',
        sets: '4',
        image: require('../assets/images/Squats.gif'),
      },
      {
        id: '2',
        name: 'Deadlifts',
        reps: '6-8',
        sets: '4',
        image: require('../assets/images/Deadlift.gif'),
      },
      {
        id: '3',
        name: 'Leg Press',
        reps: '10-12',
        sets: '3',
        image: require('../assets/images/legpress.gif'),
      },
      {
        id: '4',
        name: 'Pull-ups',
        reps: '6-8',
        sets: '4',
        image: require('../assets/images/Pullups.gif'),
      },
      {
        id: '5',
        name: 'Bent-over Rows',
        reps: '8-10',
        sets: '4',
        image: require('../assets/images/BentoverRows.gif'),
      },
    ],
  },
  {
    id: '3',
    title: 'Day 3',
    content: 'Arms and Shoulders',
    bg: 'grade3',
    exercises: [
      {
        id: '1',
        name: 'Bicep Curls',
        reps: '10-12',
        sets: '4',
        image: require('../assets/images/BicepCurls.gif'),
      },
      {
        id: '2',
        name: 'Tricep Dips',
        reps: '8-10',
        sets: '4',
        image: require('../assets/images/TricepDips.gif'),
      },
      {
        id: '3',
        name: 'Lateral Raises',
        reps: '12-15',
        sets: '3',
        image: require('../assets/images/LateralRaises.gif'),
      },
      {
        id: '4',
        name: 'Hammer Curls',
        reps: '10-12',
        sets: '3',
        image: require('../assets/images/HammerCurls.gif'),
      },
      {
        id: '5',
        name: 'Overhead Tricep Extension',
        reps: '10-12',
        sets: '3',
        image: require('../assets/images/OverheadTricepExtension.gif'),
      },
    ],
  },
  {
    id: '4',
    title: 'Day 4',
    content: 'Cardio and Core',
    bg: 'grade4',
    exercises: [
      {
        id: '1',
        name: 'Running',
        reps: '20 minutes',
        sets: '1',
        image: require('../assets/images/Running.gif'),
      },
      {
        id: '2',
        name: 'Jump Rope',
        reps: '1 minute',
        sets: '3',
        image: require('../assets/images/JumpRope.gif'),
      },
      {
        id: '3',
        name: 'Bicycle Crunches',
        reps: '15-20',
        sets: '3',
        image: require('../assets/images/bicyclecrunches.gif'),
      },
      {
        id: '4',
        name: 'Mountain Climbers',
        reps: '12-15',
        sets: '3',
        image: require('../assets/images/MountainClimbers.gif'),
      },
      {
        id: '5',
        name: 'Hanging Leg Raises',
        reps: '10-12',
        sets: '3',
        image: require('../assets/images/HangingLegRaises.gif'),
      },
    ],
  },
  {
    id: '5',
    title: 'Day 5',
    content: 'Full Body Workout',
    bg: 'grade5',
    exercises: [
      {
        id: '1',
        name: 'Burpees',
        reps: '10-12',
        sets: '3',
        image: require('../assets/images/Burpees.gif'),
      },
      {
        id: '2',
        name: 'Kettlebell Swings',
        reps: '15-20',
        sets: '3',
        image: require('../assets/images/KettlebellSwings.gif'),
      },
      {
        id: '3',
        name: 'Push-ups',
        reps: '10-12',
        sets: '4',
        image: require('../assets/images/Pushups.gif'),
      },
      {
        id: '4',
        name: 'Jumping Jacks',
        reps: '1 minute',
        sets: '3',
        image: require('../assets/images/JumpingJacks.gif'),
      },
      {
        id: '5',
        name: 'Bodyweight Squats',
        reps: '12-15',
        sets: '4',
        image: require('../assets/images/BodyweightSquats.gif'),
      },
    ],
  },
  {
    id: '6',
    title: 'Day 6',
    content: 'Legs and Core',
    bg: 'grade6',
    exercises: [
      {
        id: '1',
        name: 'Dumbbell Lunges',
        reps: '10-12',
        sets: '3',
        image: require('../assets/images/DumbellLungs.gif'),
      },
      {
        id: '2',
        name: 'Romanian Deadlifts',
        reps: '8-10',
        sets: '4',
        image: require('../assets/images/RomanianDeadlifts.gif'),
      },
      {
        id: '3',
        name: 'Leg Curls',
        reps: '12-15',
        sets: '3',
        image: require('../assets/images/LegCurls.gif'),
      },
      {
        id: '4',
        name: 'Crunches',
        reps: '15-20',
        sets: '3',
        image: require('../assets/images/Crunches.gif'),
      },
      {
        id: '5',
        name: 'Plank',
        reps: '1 minute',
        sets: '3',
        image: require('../assets/images/Plank.gif'),
      },
    ],
  },
];
